CREATE TABLE IF NOT EXISTS champion(
	id 					INTEGER 	PRIMARY KEY,
	name				TEXT		NOT NULL
);
CREATE TABLE IF NOT EXISTS summoner_spell(
	id 					INTEGER 	PRIMARY KEY,
	name				TEXT		NOT NULL
);
CREATE TABLE IF NOT EXISTS item(
	id 					INTEGER 	PRIMARY KEY,
	name 				TEXT 		NOT NULL
);
CREATE TABLE IF NOT EXISTS perk(
	id 					INTEGER 	PRIMARY KEY,
	key 				TEXT 		NOT NULL,
	icon 				TEXT 		NOT NULL,
	name 				TEXT 		NOT NULL,
	shortDesc 			TEXT 		NOT NULL,
	longDesc 			TEXT 		NOT NULL
);
CREATE TABLE IF NOT EXISTS summoner(
	_id 				INTEGER 	PRIMARY KEY AUTOINCREMENT,
	discord_id 			INTEGER 	UNIQUE,

	accountId 			TEXT		NOT NULL,
	profileIconId		INTEGER		NOT NULL,
	revisionDate		INTEGER		NOT NULL,
	name				TEXT		NOT NULL,
	id					TEXT		NOT NULL,
	puuid				TEXT		NOT NULL,
	summonerLevel		INTEGER		NOT NULL
);
CREATE TABLE IF NOT EXISTS team(
	_id 				INTEGER 	PRIMARY KEY AUTOINCREMENT,
	summoner_id_0 		INTEGER 	NOT NULL 	REFERENCES summoner(_id),
	summoner_id_1 		INTEGER 	NOT NULL 	REFERENCES summoner(_id),
	summoner_id_2 		INTEGER 	NOT NULL 	REFERENCES summoner(_id),
	summoner_id_3 		INTEGER 	NOT NULL 	REFERENCES summoner(_id),
	summoner_id_4 		INTEGER 	NOT NULL 	REFERENCES summoner(_id),
	name 				TEXT 		UNIQUE
);
CREATE TABLE IF NOT EXISTS match(
	gameCreation			INTEGER 	NOT NULL,
	gameDuration			INTEGER 	NOT NULL,
	gameEndTimestamp		INTEGER 	NOT NULL,
	gameId					INTEGER 	PRIMARY KEY,
	gameMode				TEXT 		NOT NULL,
	gameName				TEXT 		NOT NULL,
	gameStartTimestamp		INTEGER 	NOT NULL,
	gameType				TEXT 		NOT NULL,
	gameVersion				TEXT 		NOT NULL,
	mapId					INTEGER 	NOT NULL,
	platformId				TEXT 		NOT NULL,
	queueId					INTEGER 	NOT NULL,
	tournamentCode			TEXT 		NOT NULL
);
CREATE TABLE IF NOT EXISTS participant_team(
	_id 				INTEGER 	PRIMARY KEY AUTOINCREMENT,
	match_id 			INTEGER 	NOT NULL 	REFERENCES match(gameId),
	team_id 			INTEGER 	NOT NULL 	REFERENCES team(id),
	side 				TEXT 		NOT NULL,

	ban_0 				INTEGER 	REFERENCES champion(id),
	ban_1 				INTEGER 	REFERENCES champion(id),
	ban_2 				INTEGER 	REFERENCES champion(id),
	ban_3 				INTEGER 	REFERENCES champion(id),
	ban_4 				INTEGER 	REFERENCES champion(id),

	baron_first 		INTEGER 	NOT NULL,
	baron_kills 		INTEGER 	NOT NULL,
	champion_first 		INTEGER 	NOT NULL,
	champion_kills 		INTEGER 	NOT NULL,
	dragon_first 		INTEGER 	NOT NULL,
	dragon_kills 		INTEGER 	NOT NULL,
	inhibitor_first 	INTEGER 	NOT NULL,
	inhibitor_kills 	INTEGER 	NOT NULL,
	rift_herald_first 	INTEGER 	NOT NULL,
	rift_herald_kills 	INTEGER 	NOT NULL,
	tower_first 		INTEGER 	NOT NULL,
	tower_kills 		INTEGER 	NOT NULL,
	win 				INTEGER 	NOT NULL
);
CREATE TABLE IF NOT EXISTS participant(
	_id 							INTEGER 		PRIMARY KEY AUTOINCREMENT,
	match_id 						INTEGER 		NOT NULL 	REFERENCES match(gameId),
	summoner_id 					INTEGER 		NOT NULL 	REFERENCES summoner(_id),
	participant_team 				INTEGER 		NOT NULL 	REFERENCES participant_team(_id),

	assists							INTEGER			NOT NULL,
	baronKills						INTEGER			NOT NULL,
	bountyLevel						INTEGER			NOT NULL,
	champExperience					INTEGER			NOT NULL,
	champLevel						INTEGER			NOT NULL,
	championId						INTEGER			NOT NULL,
	championName					TEXT			NOT NULL,
	championTransform				INTEGER			NOT NULL,
	consumablesPurchased			INTEGER			NOT NULL,
	damageDealtToBuildings			INTEGER			NOT NULL,
	damageDealtToObjectives			INTEGER			NOT NULL,
	damageDealtToTurrets			INTEGER			NOT NULL,
	damageSelfMitigated				INTEGER			NOT NULL,
	deaths							INTEGER			NOT NULL,
	detectorWardsPlaced				INTEGER			NOT NULL,
	doubleKills						INTEGER			NOT NULL,
	dragonKills						INTEGER			NOT NULL,
	firstBloodAssist				INTEGER			NOT NULL,
	firstBloodKill					INTEGER			NOT NULL,
	firstTowerAssist				INTEGER			NOT NULL,
	firstTowerKill					INTEGER			NOT NULL,
	gameEndedInEarlySurrender		INTEGER			NOT NULL,
	gameEndedInSurrender			INTEGER			NOT NULL,
	goldEarned						INTEGER			NOT NULL,
	goldSpent						INTEGER			NOT NULL,
	individualPosition				TEXT			NOT NULL,
	inhibitorKills					INTEGER			NOT NULL,
	inhibitorTakedowns				INTEGER			NOT NULL,
	inhibitorsLost					INTEGER			NOT NULL,
	item0							INTEGER			NOT NULL,
	item1							INTEGER			NOT NULL,
	item2							INTEGER			NOT NULL,
	item3							INTEGER			NOT NULL,
	item4							INTEGER			NOT NULL,
	item5							INTEGER			NOT NULL,
	item6							INTEGER			NOT NULL,
	itemsPurchased					INTEGER			NOT NULL,
	killingSprees					INTEGER			NOT NULL,
	kills							INTEGER			NOT NULL,
	lane							TEXT			NOT NULL,
	largestCriticalStrike			INTEGER			NOT NULL,
	largestKillingSpree				INTEGER			NOT NULL,
	largestMultiKill				INTEGER			NOT NULL,
	longestTimeSpentLiving			INTEGER			NOT NULL,
	magicDamageDealt				INTEGER			NOT NULL,
	magicDamageDealtToChampions		INTEGER			NOT NULL,
	magicDamageTaken				INTEGER			NOT NULL,
	neutralMinionsKilled			INTEGER			NOT NULL,
	nexusKills						INTEGER			NOT NULL,
	nexusTakedowns					INTEGER			NOT NULL,
	nexusLost						INTEGER			NOT NULL,
	objectivesStolen				INTEGER			NOT NULL,
	objectivesStolenAssists			INTEGER			NOT NULL,
	participantId					INTEGER			NOT NULL,
	pentaKills						INTEGER			NOT NULL,
	physicalDamageDealt				INTEGER			NOT NULL,
	physicalDamageDealtToChampions	INTEGER			NOT NULL,
	physicalDamageTaken				INTEGER			NOT NULL,
	profileIcon						INTEGER			NOT NULL,
	puuid							TEXT			NOT NULL,
	quadraKills						INTEGER			NOT NULL,
	riotIdName						TEXT			NOT NULL,
	riotIdTagline					TEXT			NOT NULL,
	role							TEXT			NOT NULL,
	sightWardsBoughtInGame			INTEGER			NOT NULL,
	spell1Casts						INTEGER			NOT NULL,
	spell2Casts						INTEGER			NOT NULL,
	spell3Casts						INTEGER			NOT NULL,
	spell4Casts						INTEGER			NOT NULL,
	summoner1Casts					INTEGER			NOT NULL,
	summoner1Id						INTEGER			NOT NULL,
	summoner2Casts					INTEGER			NOT NULL,
	summoner2Id						INTEGER			NOT NULL,
	summonerId						TEXT			NOT NULL,
	summonerLevel					INTEGER			NOT NULL,
	summonerName					TEXT			NOT NULL,
	teamEarlySurrendered			INTEGER			NOT NULL,
	teamId							INTEGER			NOT NULL,
	teamPosition					TEXT			NOT NULL,
	timeCCingOthers					INTEGER			NOT NULL,
	timePlayed						INTEGER			NOT NULL,
	totalDamageDealt				INTEGER			NOT NULL,
	totalDamageDealtToChampions		INTEGER			NOT NULL,
	totalDamageShieldedOnTeammates	INTEGER			NOT NULL,
	totalDamageTaken				INTEGER			NOT NULL,
	totalHeal						INTEGER			NOT NULL,
	totalHealsOnTeammates			INTEGER			NOT NULL,
	totalMinionsKilled				INTEGER			NOT NULL,
	totalTimeCCDealt				INTEGER			NOT NULL,
	totalTimeSpentDead				INTEGER			NOT NULL,
	totalUnitsHealed				INTEGER			NOT NULL,
	tripleKills						INTEGER			NOT NULL,
	trueDamageDealt					INTEGER			NOT NULL,
	trueDamageDealtToChampions		INTEGER			NOT NULL,
	trueDamageTaken					INTEGER			NOT NULL,
	turretKills						INTEGER			NOT NULL,
	turretTakedowns					INTEGER			NOT NULL,
	turretsLost						INTEGER			NOT NULL,
	unrealKills						INTEGER			NOT NULL,
	visionScore						INTEGER			NOT NULL,
	visionWardsBoughtInGame			INTEGER			NOT NULL,
	wardsKilled						INTEGER			NOT NULL,
	wardsPlaced						INTEGER			NOT NULL,
	win								INTEGER			NOT NULL,

	perk_defence					INTEGER			NOT NULL REFERENCES perk(id),
	perk_flex						INTEGER			NOT NULL REFERENCES perk(id),
	perk_offense					INTEGER			NOT NULL REFERENCES perk(id),
	perk_style_primary_0 			INTEGER 		NOT NULL REFERENCES perk(id),
	perk_style_primary_1 			INTEGER 		NOT NULL REFERENCES perk(id),
	perk_style_primary_2 			INTEGER 		NOT NULL REFERENCES perk(id),
	perk_style_primary_3 			INTEGER 		NOT NULL REFERENCES perk(id),
	perk_style_secondary_0 			INTEGER 		NOT NULL REFERENCES perk(id),
	perk_style_secondary_1 			INTEGER 		NOT NULL REFERENCES perk(id)
);

/* items */
INSERT INTO item(id, name) VALUES
(1001, "Boots"),
(1004, "Faerie Charm"),
(1006, "Rejuvenation Bead"),
(1011, "Giant's Belt"),
(1018, "Cloak of Agility"),
(1026, "Blasting Wand"),
(1027, "Sapphire Crystal"),
(1028, "Ruby Crystal"),
(1029, "Cloth Armor"),
(1031, "Chain Vest"),
(1033, "Null-Magic Mantle"),
(1035, "Emberknife"),
(1036, "Long Sword"),
(1037, "Pickaxe"),
(1038, "B. F. Sword"),
(1039, "Hailblade"),
(1040, "Obsidian Edge"),
(1042, "Dagger"),
(1043, "Recurve Bow"),
(1052, "Amplifying Tome"),
(1053, "Vampiric Scepter"),
(1054, "Doran's Shield"),
(1055, "Doran's Blade"),
(1056, "Doran's Ring"),
(1057, "Negatron Cloak"),
(1058, "Needlessly Large Rod"),
(1082, "Dark Seal"),
(1083, "Cull"),
(1500, "Penetrating Bullets"),
(1501, "Fortification"),
(1502, "Reinforced Armor"),
(1503, "Warden's Eye"),
(1504, "Vanguard"),
(1505, "Lightning Rod"),
(1506, "Reinforced Armor"),
(1507, "Overcharged"),
(1508, "Anti-tower Socks"),
(1509, "Gusto"),
(1510, "Phreakish Gusto"),
(1511, "Super Mech Armor"),
(1512, "Super Mech Power Field"),
(1515, "Turret Plating"),
(1516, "Structure Bounty"),
(1517, "Structure Bounty"),
(1518, "Structure Bounty"),
(1519, "Structure Bounty"),
(2003, "Health Potion"),
(2010, "Total Biscuit of Everlasting Will"),
(2015, "Kircheis Shard"),
(2031, "Refillable Potion"),
(2033, "Corrupting Potion"),
(2051, "Guardian's Horn"),
(2052, "Poro-Snax"),
(2055, "Control Ward"),
(2065, "Shurelya's Battlesong"),
(2138, "Elixir of Iron"),
(2139, "Elixir of Sorcery"),
(2140, "Elixir of Wrath"),
(2403, "Minion Dematerializer"),
(2419, "Commencing Stopwatch"),
(2420, "Stopwatch"),
(2421, "Broken Stopwatch"),
(2422, "Slightly Magical Footwear"),
(2423, "Perfectly Timed Stopwatch"),
(2424, "Broken Stopwatch"),
(3001, "Evenshroud"),
(3003, "Archangel's Staff"),
(3004, "Manamune"),
(3006, "Berserker's Greaves"),
(3009, "Boots of Swiftness"),
(3011, "Chemtech Putrifier"),
(3020, "Sorcerer's Shoes"),
(3024, "Glacial Buckler"),
(3026, "Guardian Angel"),
(3031, "Infinity Edge"),
(3033, "Mortal Reminder"),
(3035, "Last Whisper"),
(3036, "Lord Dominik's Regards"),
(3040, "Seraph's Embrace"),
(3041, "Mejai's Soulstealer"),
(3042, "Muramana"),
(3044, "Phage"),
(3046, "Phantom Dancer"),
(3047, "Plated Steelcaps"),
(3050, "Zeke's Convergence"),
(3051, "Hearthbound Axe"),
(3053, "Sterak's Gage"),
(3057, "Sheen"),
(3065, "Spirit Visage"),
(3066, "Winged Moonplate"),
(3067, "Kindlegem"),
(3068, "Sunfire Aegis"),
(3070, "Tear of the Goddess"),
(3071, "Black Cleaver"),
(3072, "Bloodthirster"),
(3074, "Ravenous Hydra"),
(3075, "Thornmail"),
(3076, "Bramble Vest"),
(3077, "Tiamat"),
(3078, "Trinity Force"),
(3082, "Warden's Mail"),
(3083, "Warmog's Armor"),
(3085, "Runaan's Hurricane"),
(3086, "Zeal"),
(3089, "Rabadon's Deathcap"),
(3091, "Wit's End"),
(3094, "Rapid Firecannon"),
(3095, "Stormrazor"),
(3100, "Lich Bane"),
(3102, "Banshee's Veil"),
(3105, "Aegis of the Legion"),
(3107, "Redemption"),
(3108, "Fiendish Codex"),
(3109, "Knight's Vow"),
(3110, "Frozen Heart"),
(3111, "Mercury's Treads"),
(3112, "Guardian's Orb"),
(3113, "Aether Wisp"),
(3114, "Forbidden Idol"),
(3115, "Nashor's Tooth"),
(3116, "Rylai's Crystal Scepter"),
(3117, "Mobility Boots"),
(3119, "Winter's Approach"),
(3121, "Fimbulwinter"),
(3123, "Executioner's Calling"),
(3124, "Guinsoo's Rageblade"),
(3133, "Caulfield's Warhammer"),
(3134, "Serrated Dirk"),
(3135, "Void Staff"),
(3139, "Mercurial Scimitar"),
(3140, "Quicksilver Sash"),
(3142, "Youmuu's Ghostblade"),
(3143, "Randuin's Omen"),
(3145, "Hextech Alternator"),
(3152, "Hextech Rocketbelt"),
(3153, "Blade of The Ruined King"),
(3155, "Hexdrinker"),
(3156, "Maw of Malmortius"),
(3157, "Zhonya's Hourglass"),
(3158, "Ionian Boots of Lucidity"),
(3165, "Morellonomicon"),
(3177, "Guardian's Blade"),
(3179, "Umbral Glaive"),
(3181, "Hullbreaker"),
(3184, "Guardian's Hammer"),
(3190, "Locket of the Iron Solari"),
(3191, "Seeker's Armguard"),
(3193, "Gargoyle Stoneplate"),
(3211, "Spectre's Cowl"),
(3222, "Mikael's Blessing"),
(3330, "Scarecrow Effigy"),
(3340, "Stealth Ward"),
(3363, "Farsight Alteration"),
(3364, "Oracle Lens"),
(3400, "Your Cut"),
(3504, "Ardent Censer"),
(3508, "Essence Reaver"),
(3513, "Eye of the Herald"),
(3599, "Kalista's Black Spear"),
(3600, "Kalista's Black Spear"),
(3742, "Dead Man's Plate"),
(3748, "Titanic Hydra"),
(3801, "Crystalline Bracer"),
(3802, "Lost Chapter"),
(3814, "Edge of Night"),
(3850, "Spellthief's Edge"),
(3851, "Frostfang"),
(3853, "Shard of True Ice"),
(3854, "Steel Shoulderguards"),
(3855, "Runesteel Spaulders"),
(3857, "Pauldrons of Whiterock"),
(3858, "Relic Shield"),
(3859, "Targon's Buckler"),
(3860, "Bulwark of the Mountain"),
(3862, "Spectral Sickle"),
(3863, "Harrowing Crescent"),
(3864, "Black Mist Scythe"),
(3901, "Fire at Will"),
(500, "Silver Serpents"),
(3902, "Death's Daughter"),
(3903, "Raise Morale"),
(3916, "Oblivion Orb"),
(4005, "Imperial Mandate"),
(4401, "Force of Nature"),
(4403, "The Golden Spatula"),
(4628, "Horizon Focus"),
(4629, "Cosmic Drive"),
(4630, "Blighting Jewel"),
(4632, "Verdant Barrier"),
(4633, "Riftmaker"),
(4635, "Leeching Leer"),
(4636, "Night Harvester"),
(4637, "Demonic Embrace"),
(4638, "Watchful Wardstone"),
(4641, "Stirring Wardstone"),
(4642, "Bandleglass Mirror"),
(4643, "Vigilant Wardstone"),
(4644, "Crown of the Shattered Queen"),
(4645, "Shadowflame"),
(6029, "Ironspike Whip"),
(6035, "Silvermere Dawn"),
(6333, "Death's Dance"),
(6609, "Chempunk Chainsword"),
(6616, "Staff of Flowing Water"),
(6617, "Moonstone Renewer"),
(6630, "Goredrinker"),
(6631, "Stridebreaker"),
(6632, "Divine Sunderer"),
(6653, "Liandry's Anguish"),
(6655, "Luden's Tempest"),
(6656, "Everfrost"),
(6660, "Bami's Cinder"),
(6662, "Frostfire Gauntlet"),
(6664, "Turbo Chemtank"),
(6670, "Noonquiver"),
(6671, "Galeforce"),
(6672, "Kraken Slayer"),
(6673, "Immortal Shieldbow"),
(6675, "Navori Quickblades"),
(6676, "The Collector"),
(6677, "Rageknife"),
(6691, "Duskblade of Draktharr"),
(6692, "Eclipse"),
(6693, "Prowler's Claw"),
(6694, "Serylda's Grudge"),
(6695, "Serpent's Fang"),
(6696, "Axiom Arc"),
(7000, "Sandshrike's Claw"),
(7001, "Syzygy"),
(7002, "Draktharr's Shadowcarver"),
(7003, "Turbocharged Hexperiment"),
(7004, "Forgefire Crest"),
(7005, "Rimeforged Grasp"),
(7006, "Typhoon"),
(7007, "Wyrmfallen Sacrifice"),
(7008, "Bloodward"),
(7009, "Icathia's Curse"),
(7010, "Vespertide"),
(7011, "Upgraded Aeropack"),
(7012, "Liandry's Lament"),
(7013, "Eye of Luden"),
(7014, "Eternal Winter"),
(7015, "Ceaseless Hunger"),
(7016, "Dreamshatter"),
(7017, "Deicide"),
(7018, "Infinity Force"),
(7019, "Reliquary of the Golden Dawn"),
(7020, "Shurelya's Requiem"),
(7021, "Starcaster"),
(7022, "Seat of Command"),
(7023, "Equinox"),
(7024, "Caesura"),
(7050, "Gangplank Placeholder"),
(8001, "Anathema's Chains"),
(8020, "Abyssal Mask");

/* champions */
INSERT INTO champion(id, name) VALUES
(266, "Aatrox"),
(103, "Ahri"),
(84, "Akali"),
(166, "Akshan"),
(12, "Alistar"),
(32, "Amumu"),
(34, "Anivia"),
(1, "Annie"),
(523, "Aphelios"),
(22, "Ashe"),
(136, "Aurelion Sol"),
(268, "Azir"),
(432, "Bard"),
(53, "Blitzcrank"),
(63, "Brand"),
(201, "Braum"),
(51, "Caitlyn"),
(164, "Camille"),
(69, "Cassiopeia"),
(31, "Cho'Gath"),
(42, "Corki"),
(122, "Darius"),
(131, "Diana"),
(119, "Draven"),
(36, "Dr. Mundo"),
(245, "Ekko"),
(60, "Elise"),
(28, "Evelynn"),
(81, "Ezreal"),
(9, "Fiddlesticks"),
(114, "Fiora"),
(105, "Fizz"),
(3, "Galio"),
(41, "Gangplank"),
(86, "Garen"),
(150, "Gnar"),
(79, "Gragas"),
(104, "Graves"),
(887, "Gwen"),
(120, "Hecarim"),
(74, "Heimerdinger"),
(420, "Illaoi"),
(39, "Irelia"),
(427, "Ivern"),
(40, "Janna"),
(59, "Jarvan IV"),
(24, "Jax"),
(126, "Jayce"),
(202, "Jhin"),
(222, "Jinx"),
(145, "Kai'Sa"),
(429, "Kalista"),
(43, "Karma"),
(30, "Karthus"),
(38, "Kassadin"),
(55, "Katarina"),
(10, "Kayle"),
(141, "Kayn"),
(85, "Kennen"),
(121, "Kha'Zix"),
(203, "Kindred"),
(240, "Kled"),
(96, "Kog'Maw"),
(7, "LeBlanc"),
(64, "Lee Sin"),
(89, "Leona"),
(876, "Lillia"),
(127, "Lissandra"),
(236, "Lucian"),
(117, "Lulu"),
(99, "Lux"),
(54, "Malphite"),
(90, "Malzahar"),
(57, "Maokai"),
(11, "Master Yi"),
(21, "Miss Fortune"),
(62, "Wukong"),
(82, "Mordekaiser"),
(25, "Morgana"),
(267, "Nami"),
(75, "Nasus"),
(111, "Nautilus"),
(518, "Neeko"),
(76, "Nidalee"),
(56, "Nocturne"),
(20, "Nunu & Willump"),
(2, "Olaf"),
(61, "Orianna"),
(516, "Ornn"),
(80, "Pantheon"),
(78, "Poppy"),
(555, "Pyke"),
(246, "Qiyana"),
(133, "Quinn"),
(497, "Rakan"),
(33, "Rammus"),
(421, "Rek'Sai"),
(526, "Rell"),
(888, "Renata Glasc"),
(58, "Renekton"),
(107, "Rengar"),
(92, "Riven"),
(68, "Rumble"),
(13, "Ryze"),
(360, "Samira"),
(113, "Sejuani"),
(235, "Senna"),
(147, "Seraphine"),
(875, "Sett"),
(35, "Shaco"),
(98, "Shen"),
(102, "Shyvana"),
(27, "Singed"),
(14, "Sion"),
(15, "Sivir"),
(72, "Skarner"),
(37, "Sona"),
(16, "Soraka"),
(50, "Swain"),
(517, "Sylas"),
(134, "Syndra"),
(223, "Tahm Kench"),
(163, "Taliyah"),
(91, "Talon"),
(44, "Taric"),
(17, "Teemo"),
(412, "Thresh"),
(18, "Tristana"),
(48, "Trundle"),
(23, "Tryndamere"),
(4, "Twisted Fate"),
(29, "Twitch"),
(77, "Udyr"),
(6, "Urgot"),
(110, "Varus"),
(67, "Vayne"),
(45, "Veigar"),
(161, "Vel'Koz"),
(711, "Vex"),
(254, "Vi"),
(234, "Viego"),
(112, "Viktor"),
(8, "Vladimir"),
(106, "Volibear"),
(19, "Warwick"),
(498, "Xayah"),
(101, "Xerath"),
(5, "Xin Zhao"),
(157, "Yasuo"),
(777, "Yone"),
(83, "Yorick"),
(350, "Yuumi"),
(154, "Zac"),
(238, "Zed"),
(221, "Zeri"),
(115, "Ziggs"),
(26, "Zilean"),
(142, "Zoe"),
(143, "Zyra");

/* summoner_spells */
INSERT INTO summoner_spell(id, name) VALUES
(21, "Barrier"),
(1, "Cleanse"),
(14, "Ignite"),
(3, "Exhaust"),
(4, "Flash"),
(6, "Ghost"),
(7, "Heal"),
(13, "Clarity"),
(30, "To the King!"),
(31, "Poro Toss"),
(11, "Smite"),
(39, "Mark"),
(32, "Mark"),
(12, "Teleport"),
(54, "Placeholder"),
(55, "Placeholder and Attack-Smite");

/* perks */
INSERT INTO perk(id, key, icon, name, shortDesc, longDesc) VALUES
(8112,
"Electrocute",
"perk-images/Styles/Domination/Electrocute/Electrocute.png",
"Electrocute",
"Hitting a champion with 3 <b>separate</b> attacks or abilities in 3s deals bonus <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_AdaptiveDmg'>adaptive damage</lol-uikit-tooltipped-keyword>.",
"Hitting a champion with 3 <b>separate</b> attacks or abilities within 3s deals bonus <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_AdaptiveDmg'><font color='#48C4B7'>adaptive damage</font></lol-uikit-tooltipped-keyword>.<br><br>Damage: 30 - 180 (+0.4 bonus AD, +0.25 AP) damage.<br><br>Cooldown: 25 - 20s<br><br><hr><i>'We called them the Thunderlords, for to speak of their lightning was to invite disaster.'</i>"
),
(8124,
"Predator",
"perk-images/Styles/Domination/Predator/Predator.png",
"Predator",
"Add an active effect to your boots that grants a large boost of <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_MS'>MS</lol-uikit-tooltipped-keyword> and causes your next attack or ability to deal bonus <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_AdaptiveDmg'>adaptive damage</lol-uikit-tooltipped-keyword>.",
"Enchants your boots with the active effect '<font color='#c60300'>Predator</font>.'<br><br>Gain increased Movement Speed, ramping up to 45% Movement Speed over 1.5 seconds, while chasing enemy champions. After ramping up, damaging attacks or abilities to champions end this effect, dealing 40-120 (+<scaleAD>0.2</scaleAD> bonus AD)(+<scaleAP>0.1</scaleAP> AP) bonus <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_AdaptiveDmg'><font color='#48C4B7'>adaptive damage</font></lol-uikit-tooltipped-keyword>.<br><br>Cooldown: 90s-60s."
),
(8128,
"DarkHarvest",
"perk-images/Styles/Domination/DarkHarvest/DarkHarvest.png",
"Dark Harvest",
"Damaging a low health champion inflicts <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_AdaptiveDmg'>adaptive damage</lol-uikit-tooltipped-keyword> and harvests a soul from the victim.",
"Damaging a Champion below 50% health deals <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_AdaptiveDmg'>adaptive damage</lol-uikit-tooltipped-keyword> and harvests their soul, permanently increasing Dark Harvest's damage by 5.<br><br>Dark Harvest damage: 20-60 (based on level) (+5 damage per soul) (+0.25 bonus AD) (+0.15 AP)<br>Cooldown: 45s (resets to 1.5s on takedown)"
),
(9923,
"HailOfBlades",
"perk-images/Styles/Domination/HailOfBlades/HailOfBlades.png",
"Hail of Blades",
"Gain a large amount of Attack Speed for the first 3 attacks made against enemy champions.",
"Gain 110% Attack Speed when you attack an enemy champion for up to 3 attacks.<br><br>No more than 3s can elapse between attacks or this effect will end.<br><br>Cooldown: 8s out of combat with champions.<br><br><rules>Attack resets increase the attack limit by 1.<br>Allows you to temporarily exceed the attack speed limit.</rules>"
),
(8126,
"CheapShot",
"perk-images/Styles/Domination/CheapShot/CheapShot.png",
"Cheap Shot",
"Deal bonus true damage to enemy champions with <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_ImpairAct'>impaired movement or actions</lol-uikit-tooltipped-keyword>. ",
"Damaging champions with <b>impaired movement or actions</b> deals 10 - 45 bonus true damage (based on level).<br><br>Cooldown: 4s<br><rules>Activates on damage occurring after the impairment.</rules>"
),
(8139,
"TasteOfBlood",
"perk-images/Styles/Domination/TasteOfBlood/GreenTerror_TasteOfBlood.png",
"Taste of Blood",
"Heal when you damage an enemy champion.",
"Heal when you damage an enemy champion.<br><br>Healing: 18-35 (+0.2 bonus AD, +0.1 AP) health (based on level)<br><br>Cooldown: 20s"
),
(8143,
"SuddenImpact",
"perk-images/Styles/Domination/SuddenImpact/SuddenImpact.png",
"Sudden Impact",
"Gain a burst of Lethality and Magic Penetration after using a dash, leap, blink, teleport, or when leaving stealth.",
"After exiting stealth or using a dash, leap, blink, or teleport, dealing any damage to a champion grants you 7 Lethality and 6 Magic Penetration for 5s.<br><br>Cooldown: 4s"
),
(8136,
"ZombieWard",
"perk-images/Styles/Domination/ZombieWard/ZombieWard.png",
"Zombie Ward",
"<lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>Takedowns</lol-uikit-tooltipped-keyword> on enemy Wards cause friendly Zombie Wards to sprout from their corpses. Gain permanent AD or AP, <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'>adaptive</lol-uikit-tooltipped-keyword> for each Zombie Ward spawned plus bonus upon completion.",
"<lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>Takedowns</lol-uikit-tooltipped-keyword> on enemy Wards cause friendly Zombie Wards to sprout from their corpses.<br><br>Gain an <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'><font color='#48C4B7'>adaptive</font></lol-uikit-tooltipped-keyword> bonus of 1.2 Attack Damage or 2 Ability Power for every Zombie Ward spawned, up to 10. <br><br>After spawning 10 Zombie Wards, additionally gain 10 adaptive force.<br><br>Zombie Wards are visible, last for 120s and do not count towards your ward limit."
),
(8120,
"GhostPoro",
"perk-images/Styles/Domination/GhostPoro/GhostPoro.png",
"Ghost Poro",
"When your wards expire, they leave behind a Ghost Poro. The Ghost Poro grants vision until discovered. Gain permanent AD or AP, <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'>adaptive</lol-uikit-tooltipped-keyword> for each Ghost Poro and when your Ghost Poro spots an enemy champion, plus bonus upon completion.",
"When your wards expire, they leave behind a Ghost Poro, which grants vision for 60s. Nearby enemy champions scare the Ghost Poro away.<br><br>Gain an <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'><font color='#48C4B7'>adaptive</font></lol-uikit-tooltipped-keyword> bonus of 1.2 Attack Damage or 2 Ability Power for every Ghost Poro spawned and when your Ghost Poro spots an enemy champion up to 10 stacks. <br><br>After gaining 10 stacks, additionally gain 10 adaptive force."
),
(8138,
"EyeballCollection",
"perk-images/Styles/Domination/EyeballCollection/EyeballCollection.png",
"Eyeball Collection",
"Collect eyeballs for champion <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>takedowns</lol-uikit-tooltipped-keyword>. Gain permanent AD or AP, <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'>adaptive</lol-uikit-tooltipped-keyword> for each eyeball plus bonus upon collection completion.",
"Collect eyeballs for champion takedowns. Gain an <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'><font color='#48C4B7'>adaptive</font></lol-uikit-tooltipped-keyword> bonus of 1.2 Attack Damage or 2 Ability Power, per eyeball collected. <br><br>Upon completing your collection at 10 eyeballs, additionally gain an <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'><font color='#48C4B7'>adaptive</font></lol-uikit-tooltipped-keyword> bonus of 6 Attack Damage, or 10 Ability Power.<br><br>Collect 1 eyeball per champion takedown."
),
(8135,
"RavenousHunter",
"perk-images/Styles/Domination/RavenousHunter/RavenousHunter.png",
"Ravenous Hunter",
"<b>Unique</b> <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>takedowns</lol-uikit-tooltipped-keyword> grant permanent healing from ability damage. ",
"Heal for a percentage of the damage dealt by your abilities.<br>Healing: 1.5% + 2.5% per <i>Bounty Hunter</i> stack. <br><br><i>Bounty Hunter</i> stacks are earned the first time you get a takedown on each enemy champion.<br><rules><br>Healing reduced to one third for Area of Effect abilities.</rules>"
),
(8134,
"IngeniousHunter",
"perk-images/Styles/Domination/IngeniousHunter/IngeniousHunter.png",
"Ingenious Hunter",
"<b>Unique</b> <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>takedowns</lol-uikit-tooltipped-keyword> grant permanent Active Item <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_CDR'>CDR</lol-uikit-tooltipped-keyword> (includes Trinkets).",
"Gain 15% <b>Active Item CDR</b> plus an additional 5% per <i>Bounty Hunter</i> stack (includes Trinkets).<br><br><i>Bounty Hunter</i> stacks are earned the first time you get a takedown on each enemy champion."
),
(8105,
"RelentlessHunter",
"perk-images/Styles/Domination/RelentlessHunter/RelentlessHunter.png",
"Relentless Hunter",
"<b>Unique</b> <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>takedowns</lol-uikit-tooltipped-keyword> grant permanent <b>out of combat <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_MS'>MS</lol-uikit-tooltipped-keyword></b>. ",
"Gain 10 <b>out of combat Movement Speed</b> plus 9 per <i>Bounty Hunter</i> stack.<br><br><i>Bounty Hunter</i> stacks are earned the first time you get a takedown on each enemy champion."
),
(8106,
"UltimateHunter",
"perk-images/Styles/Domination/UltimateHunter/UltimateHunter.png",
"Ultimate Hunter",
"<b>Unique</b> <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>takedowns</lol-uikit-tooltipped-keyword> grant permanent cooldown reduction on your Ultimate. ",
"Your ultimate gains 5% <b>reduced cooldown,</b> plus an additional 4% per <i>Bounty Hunter</i> stack.<br><br><i>Bounty Hunter</i> stacks are earned the first time you get a takedown on each enemy champion."
),
(8351,
"GlacialAugment",
"perk-images/Styles/Inspiration/GlacialAugment/GlacialAugment.png",
"Glacial Augment",
"Your first attack against an enemy champion slows them (per unit cooldown). Slowing champions with active items shoots a freeze ray at them, creating a lingering slow zone.",
"Basic attacking a champion slows them for 2s. The slow increases in strength over its duration.<li><i>Ranged</i>: Ranged attacks slow by up to 30% - 40%</li> <li><i>Melee</i>: Melee attacks slow by up to 45% - 55%</li><br>Slowing a champion with active items shoots a freeze ray through them, freezing the nearby ground for 5s, slowing all units inside by 60%.<br><br>Cooldown: 7-4s per unit"
),
(8360,
"UnsealedSpellbook",
"perk-images/Styles/Inspiration/UnsealedSpellbook/UnsealedSpellbook.png",
"Unsealed Spellbook",
"Swap Summoner Spells while out of combat. Swapping to unique Summoner Spells will increase the rate at which you can make future swaps.",
"Swap one of your equipped Summoner Spells to a new, single use Summoner Spell. Each unique Summoner Spell you swap to permanently decreases your swap cooldown by 25s (initial swap cooldown is at 5 mins). <br><br>Your first swap becomes available at 6 mins. <br><rules><br>Summoner Spells can only be swapped while out of combat. <br>After using a swapped Summoner Spell you must swap 3 more times before the first can be selected again. </rules>"
),
(8358,
"MasterKey",
"perk-images/Styles/Inspiration/MasterKey/MasterKey.png",
"Prototype: Omnistone",
"Periodically grants a single use of another random keystone.",
"Periodically grants a single use of another random keystone.<br><br>5-3  second cooldown between using a keystone and gaining the next. (9-7 seconds for ranged users)<br><br><rules><br>After 40 seconds of not using a given keystone, Omnistone will re-roll when you exit champion combat.<br>Aftershock is only available to champions who have learned a basic spell that can trigger it.<br>Predator is only available to champions who have already purchased boots.<br></rules>"
),
(8306,
"HextechFlashtraption",
"perk-images/Styles/Inspiration/HextechFlashtraption/HextechFlashtraption.png",
"Hextech Flashtraption",
"While Flash is on cooldown it is replaced by <i>Hexflash</i>.<br><br><i>Hexflash</i>: Channel, then blink to a new location.",
"While Flash is on cooldown it is replaced by <i>Hexflash</i>.<br><br><i>Hexflash</i>: Channel for 2s to blink to a new location.<br><br>Cooldown: 20s. Goes on a 10s cooldown when you enter champion combat."
),
(8304,
"MagicalFootwear",
"perk-images/Styles/Inspiration/MagicalFootwear/MagicalFootwear.png",
"Magical Footwear",
"You get free boots at 12 min but you cannot buy boots before then. Each <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>takedown</lol-uikit-tooltipped-keyword> you get makes your boots come 45s sooner.",
"You get free Slightly Magical Boots at 12 min, but you cannot buy boots before then. For each takedown you acquire the boots 45s sooner.<br><br>Slightly Magical Boots give you an additional +10 Movement Speed."
),
(8313,
"PerfectTiming",
"perk-images/Styles/Inspiration/PerfectTiming/PerfectTiming.png",
"Perfect Timing",
"Gain a free Commencing Stopwatch. After 14 minutes, it can be used for a one time <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Stasis'>Stasis</lol-uikit-tooltipped-keyword> effect. <br><br>Each <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>takedown</lol-uikit-tooltipped-keyword> you get shortens this timer by 120 seconds.",
"Begin the game with a Commencing Stopwatch that transforms into a Stopwatch after 14 minutes. Each takedown you acquire reduces this timer by 120 seconds.<br><br>Stopwatch can be used for a one time 2.5 second Stasis effect."
),
(8321,
"FuturesMarket",
"perk-images/Styles/Inspiration/FuturesMarket/FuturesMarket.png",
"Future's Market",
"You can enter debt to buy items.",
"You can enter debt to buy items. The amount you can borrow increases over time.<br><br>Lending Fee: 50 gold"
),
(8316,
"MinionDematerializer",
"perk-images/Styles/Inspiration/MinionDematerializer/MinionDematerializer.png",
"Minion Dematerializer",
"Start the game with 3 Minion Dematerializers. Killing minions with the item gives permanent bonus damage vs. that minion type.",
"Start the game with 3 Minion Dematerializers that kill and absorb lane minions instantly. Minion Dematerializers are on cooldown for the first 180s of the game.<br><br>Absorbing a minion increases your damage by +6% against that type of minion permanently, and an extra +3% for each additional minion of that type absorbed.<br>"
),
(8345,
"BiscuitDelivery",
"perk-images/Styles/Inspiration/BiscuitDelivery/BiscuitDelivery.png",
"Biscuit Delivery",
"Gain a free Biscuit every 2 min, until 6 min. Consuming or selling a Biscuit permanently increases your max mana and restores health and mana.",
"Biscuit Delivery: Gain a Total Biscuit of Everlasting Will every 2 mins, until 6 min.<br><br>Biscuits restore 10% of your missing health and mana. Consuming or selling a Biscuit permanently increases your mana cap by 50. <br><br><i>Manaless:</i> Champions without mana restore 12% missing health instead."
),
(8347,
"CosmicInsight",
"perk-images/Styles/Inspiration/CosmicInsight/CosmicInsight.png",
"Cosmic Insight",
"+5% <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_CDR'>CDR</lol-uikit-tooltipped-keyword><br>+5% Max CDR<br>+5% Summoner Spell CDR<br>+5% Item CDR",
"+5% CDR<br>+5% Max CDR<br>+5% Summoner Spell CDR<br>+5% Item CDR"
),
(8410,
"ApproachVelocity",
"perk-images/Styles/Resolve/ApproachVelocity/ApproachVelocity.png",
"Approach Velocity",
"Bonus <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_MS'>MS</lol-uikit-tooltipped-keyword> towards nearby enemy champions that are <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_ImpairMov'>movement impaired</lol-uikit-tooltipped-keyword>, increased for enemy champions that you impair.",
"Gain 7.5% Movement Speed towards nearby enemy champions that are movement impaired. This bonus is increased to 15% Movement Speed for any enemy champion that you impair. <br><br>Activation Range for CC from allies: 1000"
),
(8352,
"TimeWarpTonic",
"perk-images/Styles/Inspiration/TimeWarpTonic/TimeWarpTonic.png",
"Time Warp Tonic",
"Potions and biscuits grant some restoration immediately. Gain <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_MS'>MS</lol-uikit-tooltipped-keyword>  while under their effects.",
"Consuming a potion or biscuit grants 50% of its health or mana restoration immediately, but puts that consumable on a short cooldown. In addition, gain 5% Movement Speed while under their effects.<br><br>Cooldown: equal to the duration of the consumable."
),
(8005,
"PressTheAttack",
"perk-images/Styles/Precision/PressTheAttack/PressTheAttack.png",
"Press the Attack",
"Hitting an enemy champion 3 consecutive times makes them vulnerable, dealing bonus damage and causing them to take more damage from all sources for 6s.",
"Hitting an enemy champion with 3 consecutive basic attacks deals 40 - 180 bonus <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_AdaptiveDmg'><font color='#48C4B7'>adaptive damage</font></lol-uikit-tooltipped-keyword> (based on level) and makes them vulnerable, increasing the damage they take by 8 - 12% from all sources for 6s."
),
(8008,
"LethalTempo",
"perk-images/Styles/Precision/LethalTempo/LethalTempoTemp.png",
"Lethal Tempo",
"1.5s after damaging a champion gain a large amount of Attack Speed. Lethal Tempo allows you to temporarily exceed the attack speed limit.",
"1.5s after damaging a champion gain 40 - 110% Attack Speed (based on level) for 3s. Attacking a champion extends the effect to 6s.<br><br>Cooldown: 6s<br><br>Lethal Tempo allows you to temporarily exceed the attack speed limit."
),
(8021,
"FleetFootwork",
"perk-images/Styles/Precision/FleetFootwork/FleetFootwork.png",
"Fleet Footwork",
"Attacking and moving builds Energy stacks. At 100 stacks, your next attack heals you and grants increased <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_MS'>MS</lol-uikit-tooltipped-keyword>.",
"Attacking and moving builds Energy stacks. At 100 stacks, your next attack is Energized<br><br>Energized attacks heal you for 3 - 60 (+0.3 Bonus AD, +0.3 AP) and grant +20% movement speed for 1s.<br><br>Healing from minions is 20% effective for Ranged Champions."
),
(8010,
"Conqueror",
"perk-images/Styles/Precision/Conqueror/Conqueror.png",
"Conqueror",
"Gain stacks of adaptive force when attacking enemy champions. After reaching 12 stacks, heal for a portion of damage you deal to champions.",
"Basic attacks or spells that deal damage to an enemy champion grant 2 stacks of Conqueror for 6s, gaining 1.7-4.2 <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'><font color='#48C4B7'>Adaptive Force</font></lol-uikit-tooltipped-keyword> per stack. Stacks up to 12 times. Ranged champions gain only 1 stack per basic attack.<br><br>When fully stacked, heal for 15% of the damage you deal to champions (8% for ranged champions)."
),
(9101,
"Overheal",
"perk-images/Styles/Precision/Overheal.png",
"Overheal",
"Excess healing on you becomes a shield.",
"Excess healing on you becomes a shield, for up to 10 <scaleHealth>(+10% Max Health)</scaleHealth>.<br><br>Shield is built up from 20 to 100% of excess healing from yourself or any ally."
),
(9111,
"Triumph",
"perk-images/Styles/Precision/Triumph.png",
"Triumph",
"<lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>Takedowns</lol-uikit-tooltipped-keyword> restore 12% of your missing health and grant an additional 20 gold. ",
"Takedowns restore 12% of your missing health and grant an additional 20 gold. <br><br><hr><br><i>'The most dangerous game brings the greatest glory.' <br>—Noxian Reckoner</i>"
),
(8009,
"PresenceOfMind",
"perk-images/Styles/Precision/PresenceOfMind/PresenceOfMind.png",
"Presence of Mind",
"Takedowns restore mana or energy and increase their maximum amounts. ",
"Takedowns restore 20% of your maximum mana or energy and increase your maximum mana by 100 (up to 500) or your maximum energy by 10 (up to 50). "
),
(9104,
"LegendAlacrity",
"perk-images/Styles/Precision/LegendAlacrity/LegendAlacrity.png",
"Legend: Alacrity",
"<lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>Takedowns</lol-uikit-tooltipped-keyword> on enemies grant permanent <b>Attack Speed</b>. ",
"Gain 3% attack speed plus an additional 1.5% for every <i>Legend</i> stack (<statGood>max 10 stacks</statGood>).<br><br>Earn progress toward <i>Legend</i> stacks for every champion takedown, epic monster takedown, large monster kill, and minion kill."
),
(9105,
"LegendTenacity",
"perk-images/Styles/Precision/LegendTenacity/LegendTenacity.png",
"Legend: Tenacity",
"<lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>Takedowns</lol-uikit-tooltipped-keyword> on enemies grant permanent <b>Tenacity</b>. ",
"Gain 5% tenacity plus an additional 2.5% for every <i>Legend</i> stack (<statGood>max 10 stacks</statGood>).<br><br>Earn progress toward <i>Legend</i> stacks for every champion takedown, epic monster takedown, large monster kill, and minion kill."
),
(9103,
"LegendBloodline",
"perk-images/Styles/Precision/LegendBloodline/LegendBloodline.png",
"Legend: Bloodline",
"<lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Takedown'>Takedowns</lol-uikit-tooltipped-keyword> on enemies grant permanent<b> Lifesteal</b>. Weaker earlier but stronger later game than other Legend Runes.",
"Gain 0.6% life steal for every <i>Legend</i> stack (<statGood>max 20 stacks</statGood>).<br><br>Earn progress toward <i>Legend</i> stacks for every champion takedown, epic monster takedown, large monster kill, and minion kill."
),
(8014,
"CoupDeGrace",
"perk-images/Styles/Precision/CoupDeGrace/CoupDeGrace.png",
"Coup de Grace",
"Deal more damage to low health enemy champions.",
"Deal 8% more damage to champions who have less than 40% health."
),
(8017,
"CutDown",
"perk-images/Styles/Precision/CutDown/CutDown.png",
"Cut Down",
"Deal more damage to champions with more max health than you.",
"Deal 5% to 15% more damage to champions, based on how much more max health they have than you.<br><br><rules>Bonus damage scales up linearly against enemies with 10% to 100% more max health than you.</rules>"
),
(8299,
"LastStand",
"perk-images/Styles/Sorcery/LastStand/LastStand.png",
"Last Stand",
"Deal more damage to champions while you are low on health.",
"Deal 5% - 11% increased damage to champions while you are below 60% health. Max damage gained at 30% health."
),
(8437,
"GraspOfTheUndying",
"perk-images/Styles/Resolve/GraspOfTheUndying/GraspOfTheUndying.png",
"Grasp of the Undying",
"Every 4s your next attack on a champion deals bonus magic damage, heals you, and permanently increases your health.",
"Every 4s in combat, your next basic attack on a champion will:<li>Deal bonus magic damage equal to 4% of your max health</li><li>Heals you for 2% of your max health</li><li>Permanently increase your health by 5</li><br><rules><i>Ranged Champions:</i> Damage, healing, and permanent health gained reduced by 40%.</rules><br>"
),
(8439,
"Aftershock",
"perk-images/Styles/Resolve/VeteranAftershock/VeteranAftershock.png",
"Aftershock",
"After <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Immobilize'>immobilizing</lol-uikit-tooltipped-keyword> an enemy champion gain defenses and later deal a burst of magic damage around you.",
"After immobilizing an enemy champion, increase your Armor and Magic Resist by 35 + 80% of your Bonus Resists for 2.5s. Then explode, dealing magic damage to nearby enemies.<br><br>Damage: 25 - 120 (+8% of your bonus health)<br>Cooldown: 20s<br><br>Resistance bonus from Aftershock capped at: 80-150 (based on level)<br>"
),
(8465,
"Guardian",
"perk-images/Styles/Resolve/Guardian/Guardian.png",
"Guardian",
"Guard allies you cast spells on and those that are very nearby. If you or a guarded ally would take damage based on level, you're both granted a shield.",
"<i>Guard</i> allies within 350 units of you, and allies you target with spells for 2.5s. While <i>Guarding</i>, if you or the ally take more than a small amount of damage over the duration of the <i>Guard</i>, both of you gain a shield for 1.5s.<br><br>Cooldown: <scaleLevel>70 - 40</scaleLevel> seconds<br>Shield: <scaleLevel>70 - 150</scaleLevel> + <scaleAP>25%</scaleAP> of your ability power + <scalehealth>12%</scalehealth> of your bonus health<br>Proc Threshold: <scaleLevel>90 - 250</scaleLevel> postmitigation damage"
),
(8446,
"Demolish",
"perk-images/Styles/Resolve/Demolish/Demolish.png",
"Demolish",
"Charge up a powerful attack against a tower while near it.",
"Charge up a powerful attack against a tower over 3s, while within 600 range of it. The charged attack deals 100 (+35% of your max health) bonus physical damage. <br><br>Cooldown: 45s"
),
(8463,
"FontOfLife",
"perk-images/Styles/Resolve/FontOfLife/FontOfLife.png",
"Font of Life",
"<lol-uikit-tooltipped-keyword key='LinkTooltip_Description_ImpairMov'>Impairing</lol-uikit-tooltipped-keyword> the movement of an enemy champion marks them. Your allies heal when attacking champions you've marked. ",
"Impairing the movement of an enemy champion marks them for 4s.<br><br>Ally champions who attack marked enemies heal for 5 + 1% of your max health over 2s. "
),
(8401,
"ShieldBash",
"perk-images/Styles/Resolve/MirrorShell/MirrorShell.png",
"Shield Bash",
"Whenever you gain a shield, your next basic attack against a champion deals bonus <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'><font color='#48C4B7'>adaptive</font></lol-uikit-tooltipped-keyword> damage.",
"While shielded, gain <scaleLevel>1 - 10</scaleLevel> Armor and Magic Resist based on Level.<br><br>Whenever you gain a new shield,  your next basic attack against a champion deals <scaleLevel>5 - 30</scaleLevel> <scaleHealth>(+1.5% Bonus Health)</scaleHealth> <scaleMana>(+8.5% New Shield Amount)</scaleMana> bonus <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'><font color='#48C4B7'>adaptive</font></lol-uikit-tooltipped-keyword> damage.<br><br>You have up to 2s after the shield expires to use this effect."
),
(8429,
"Conditioning",
"perk-images/Styles/Resolve/Conditioning/Conditioning.png",
"Conditioning",
"After 12 min gain +9 Armor and +9 Magic Resist and increase your Armor and Magic Resist by 5%.",
"After 12 min gain +9 Armor and +9 Magic Resist and increase your Armor and Magic Resist by 5%."
),
(8444,
"SecondWind",
"perk-images/Styles/Resolve/SecondWind/SecondWind.png",
"Second Wind",
"After taking damage from an enemy champion heal back some missing health over time. ",
"After taking damage from an enemy champion, heal for 4% of your missing health +6 over 10s."
),
(8473,
"BonePlating",
"perk-images/Styles/Resolve/BonePlating/BonePlating.png",
"Bone Plating",
"After taking damage from an enemy champion, the next 3 spells or attacks you receive from them deal 30-60 less damage.<br><br><br>Duration: 1.5s<br>Cooldown: 45s",
"After taking damage from an enemy champion, the next 3 spells or attacks you receive from them deal 30-60 less damage.<br><br><br>Duration: 1.5s<br>Cooldown: 45s"
),
(8451,
"Overgrowth",
"perk-images/Styles/Resolve/Overgrowth/Overgrowth.png",
"Overgrowth",
"Gain permanent max health when minions or monsters die near you.",
"Absorb life essence from monsters or enemy minions that die near you, permanently gaining 3 maximum health for every 8.<br><br>When you've absorbed 120 monsters or enemy minions, gain an additional 3.5% maximum health."
),
(8453,
"Revitalize",
"perk-images/Styles/Resolve/Revitalize/Revitalize.png",
"Revitalize",
"Heals and shields you cast or receive are 5% stronger and increased by an additional 10% on low health targets.",
"Heals and shields you cast or receive are 5% stronger and increased by an additional 10% on targets below 40% health."
),
(8242,
"Unflinching",
"perk-images/Styles/Sorcery/Unflinching/Unflinching.png",
"Unflinching",
"Gain a small amount of tenacity that increases with missing health. ",
"Gain 10% Tenacity and 10% Slow Resist. These values increase by up to an additional 20% Tenacity and 20% Slow Resist based on missing health. Maximum value achieved at 30% health. "
),
(8214,
"SummonAery",
"perk-images/Styles/Sorcery/SummonAery/SummonAery.png",
"Summon Aery",
"Your attacks and abilities send Aery to a target, damaging enemies or shielding allies.",
"Damaging enemy champions with basic attacks or abilities sends Aery to them, dealing 10 - 40 based on level (+<scaleAP>0.1 AP</scaleAP>) (+<scaleAD>0.15 bonus AD</scaleAD>).<br><br>Empower or protecting allies with abilities sends Aery to them, shielding them for 35 - 80 based on level (+<scaleAP>0.25 AP</scaleAP>) (+<scaleAD>0.4 bonus AD</scaleAD>).<br><br>Aery cannot be sent out again until she returns to you."
),
(8229,
"ArcaneComet",
"perk-images/Styles/Sorcery/ArcaneComet/ArcaneComet.png",
"Arcane Comet",
"Damaging a champion with an ability hurls a damaging comet at their location.",
"Damaging a champion with an ability hurls a comet at their location, or, if Arcane Comet is on cooldown, reduces its remaining cooldown.<br><br><lol-uikit-tooltipped-keyword key='LinkTooltip_Description_AdaptiveDmg'><font color='#48C4B7'>Adaptive Damage</font></lol-uikit-tooltipped-keyword>: 30 - 100 based on level (<scaleAP>+0.2 AP</scaleAP> and <scaleAD>+0.35 bonus AD</scaleAD>)<br>Cooldown: 20 - 8s<br><rules><br>Cooldown Reduction:<br>Single Target: 20%.<br>Area of Effect: 10%.<br>Damage over Time: 5%.<br></rules>"
),
(8230,
"PhaseRush",
"perk-images/Styles/Sorcery/PhaseRush/PhaseRush.png",
"Phase Rush",
"Hitting an enemy champion with 3 <b>separate</b> attacks or abilities grants a burst of <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_MS'>MS</lol-uikit-tooltipped-keyword>. ",
"Hitting an enemy champion with 3 attacks or <b>separate</b> abilities within 4s grants 25 - 40% Movement Speed based on level and 75% Slow Resistance. <br><br>Movement speed is increased to 40 - 60% for Melee champions.<br><br>Duration: 3s<br>Cooldown: 15s"
),
(8224,
"NullifyingOrb",
"perk-images/Styles/Sorcery/NullifyingOrb/Pokeshield.png",
"Nullifying Orb",
"Gain a magic damage shield when taken to low health by magic damage.",
"When you take magic damage that would reduce your Health below 30%, gain a shield that absorbs 40 - 120 magic damage based on level (<scaleAP>+0.1 AP</scaleAP> and <scaleAD>+0.15 bonus AD</scaleAD>) for 4s.<br><br>Cooldown: 60s"
),
(8226,
"ManaflowBand",
"perk-images/Styles/Sorcery/ManaflowBand/ManaflowBand.png",
"Manaflow Band",
"Hitting an enemy champion with an ability permanently increases your maximum mana by 25, up to 250 mana.<br><br>After reaching 250 bonus mana, restore 1% of your missing mana every 5 seconds.",
"Hitting an enemy champion with an ability permanently increases your maximum mana by 25, up to 250 mana.<br><br>After reaching 250 bonus mana, restore 1% of your missing mana every 5 seconds.<br><br>Cooldown: 15 seconds"
),
(8275,
"NimbusCloak",
"perk-images/Styles/Sorcery/NimbusCloak/6361.png",
"Nimbus Cloak",
"After casting a Summoner Spell, gain a short movement speed increase that allows you to pass through units.",
"After casting a Summoner Spell, gain a movement speed increase that lasts for 2.5s and allows you to pass through units.<br><br>Increase: 10% - 30% Movement Speed based on the Summoner Spell's cooldown. (Higher cooldown Summoner Spells grant more Movement Speed). "
),
(8210,
"Transcendence",
"perk-images/Styles/Sorcery/Transcendence/Transcendence.png",
"Transcendence",
"Gain 10% <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_CDR'>CDR</lol-uikit-tooltipped-keyword> when you reach level 10. Excess CDR becomes AP or AD, <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'>adaptive</lol-uikit-tooltipped-keyword>.",
"Gain 10% CDR when you reach level 10.<br><br>Each percent of CDR exceeding the CDR limit is converted to an <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'><font color='#48C4B7'>adaptive</font></lol-uikit-tooltipped-keyword> bonus of 1.2 Attack Damage or 2 Ability Power."
),
(8234,
"Celerity",
"perk-images/Styles/Sorcery/Celerity/CelerityTemp.png",
"Celerity",
"All movement speed bonuses are 7% more effective on you and gain 1% Movement Speed.",
"All movement bonuses are 7% more effective on you and gain 1% Movement Speed."
),
(8233,
"AbsoluteFocus",
"perk-images/Styles/Sorcery/AbsoluteFocus/AbsoluteFocus.png",
"Absolute Focus",
"While above 70% health, gain extra <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_AdaptiveDmg'>adaptive damage</lol-uikit-tooltipped-keyword>.",
"While above 70% health, gain an <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'><font color='#48C4B7'>adaptive</font></lol-uikit-tooltipped-keyword> bonus of up to 18 Attack Damage or 30 Ability Power (based on level). <br><br>Grants 1.8 Attack Damage or 3 Ability Power at level 1. "
),
(8237,
"Scorch",
"perk-images/Styles/Sorcery/Scorch/Scorch.png",
"Scorch",
"Your first damaging ability hit every 10s burns champions.",
"Your next damaging ability hit sets champions on fire dealing 15 - 35 bonus magic damage based on level after 1s.<br><br>Cooldown: 10s"
),
(8232,
"Waterwalking",
"perk-images/Styles/Sorcery/Waterwalking/Waterwalking.png",
"Waterwalking",
"Gain <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_MS'>MS</lol-uikit-tooltipped-keyword> and AP or AD, <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'>adaptive</lol-uikit-tooltipped-keyword> in the river.",
"Gain 25 Movement Speed and an <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'><font color='#48C4B7'>adaptive</font></lol-uikit-tooltipped-keyword> bonus of up to 18 Attack Damage or 30 Ability Power (based on level) when in the river.<br><br><hr><br><i>May you be as swift as the rushing river and agile as a startled Rift Scuttler.</i><br>"
),
(8236,
"GatheringStorm",
"perk-images/Styles/Sorcery/GatheringStorm/GatheringStorm.png",
"Gathering Storm",
"Gain increasing amounts of AD or AP, <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'>adaptive</lol-uikit-tooltipped-keyword> over the course of the game.",
"Every 10 min gain AP or AD, <lol-uikit-tooltipped-keyword key='LinkTooltip_Description_Adaptive'><font color='#48C4B7'>adaptive</font></lol-uikit-tooltipped-keyword>.<br><br><i>10 min</i>: + 8 AP or 5 AD <br><i>20 min</i>: + 24 AP or 14 AD<br><i>30 min</i>: + 48 AP or 29 AD<br><i>40 min</i>: + 80 AP or 48 AD<br><i>50 min</i>: + 120 AP or 72 AD<br><i>60 min</i>: + 168 AP or 101 AD<br>etc..."
);				
